apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django
spec:
  project: default
  source:
    path: helm/library-management-system
    repoURL: https://github.com/KanimozhiMurugesan26/DevOps-Project.git
    targetRevision: HEAD
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
